# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick Tobey
tagline:          Words arranged in a Meaningful Order
url:              http://nicktobey.me
paginate:         1
baseurl:          /
author:
  name:           Nick Tobey
  url:            http://nicktobey.me
  email:          ndtobey3@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/rainbowPhoenix/rainbowPhoenix.github.io

